spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/manager
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      open-in-view: false

logging.level:
  org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    include-binding-errors: always